blog/urls.py
from django.urls import path
from . import views
app_name='blog'

urlpatterns = [
    path('',views.PostListView.as_view(),name='post_list'),
    path('post/create',views.PostCreateView.as_view(),name='post_create'),
    path('drafts/',views.DraftList.as_view(),name='draft_list'),
    path('post/publish/<int:pk>',views.post_publish,name='publish'),
    path('post/detail/<int:pk>',views.PostDetailView.as_view(),name='post_detail'),
    path('post/update/<int:pk>',views.PostUpdateView.as_view(),name='post_update'),
    path('post/delete/<int:pk>',views.PostDeleteView.as_view(),name='post_delete'),
    path('comment/add/<int:pk>',views.add_comment_to_post,name='add_comment'),
    path('comment/approve/<int:pk>',views.comment_approve,name='approve_comment'),
    path('comment/delete/<int:pk>',views.comment_delete,name='delete_comment'),

]

day_13_7/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from blog import views as vi
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('accounts/login',views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/',vi.user_logout,name='logout')
]

blog/models.py
from django.db import models
from django.utils import timezone

from django.urls import reverse
from django.shortcuts import redirect
# Create your models here.

#Post Model
class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse('blog:post_list')

    def publish(self):
        self.published_date=timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def approve_comment(self):
        return self.comments.filter(approved_comment=True)

#Comment Model
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments',on_delete=models.CASCADE)
    author = models.CharField(max_length=100)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def get_absolute_url(self):
        reverse('blog:post_list')

    def approve(self):
        self.approved_comment=True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from . import models

class PostForm(forms.ModelForm):
    class Meta():
        model = models.Post
        fields = ('author','title','text')

        widgets = {
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):
    class Meta():
        model = models.Comment
        fields = ('author','text')

        widgets = {
            'author': forms.TextInput(attrs={'class':'textinputclass'}),
            'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . forms import CommentForm,PostForm

from django.utils import timezone
from . models import Comment,Post

from django.views import generic
from django.urls import reverse, reverse_lazy

from django.contrib.auth import login,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# Create your views here.

def user_logout(request):
    logout(request)
    return redirect('blog:post_list')

class PostListView(generic.ListView):
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_list.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(generic.DetailView):
    model = Post

class PostCreateView(generic.CreateView,LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post
    form_class = PostForm

class PostUpdateView(generic.UpdateView, LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    model = Post
    fields = ('title','text')

class PostDeleteView(generic.DeleteView, LoginRequiredMixin):
    login_url = '/login/'
    model = Post
    success_url = reverse_lazy('blog:post_list')

class DraftList(generic.ListView, LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name='blog/post_list.html'
    model = Post
    context_object_name = 'post'
    template_name = 'blog/post_draft_list.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=post.pk)

@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method=='POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request,'blog/comment_form.html',{'form':form})

@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(Comment,pk=pk)
    post_pk = comment.post.pk
    comment.approve()
    return redirect('blog:post_detail',pk=post_pk)

@login_required
def comment_delete(request,pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail',pk=post_pk)

blog/templates/blog/base.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{% url 'blog:post_list'%}" class="navbar-link">My Blog</a>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'blog:post_create'%}" class="nav-link">New Post</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'blog:draft_list'%}" class="nav-link">Drafts</a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">Welcome{{user.username}}</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'logout'%}" class="nav-link">LogOut</a>
          </li>

          {% else %}
            <a class="nav-link" href="{% url 'login'%}">Login</a>
          </li>
          {% endif %}
        </ul>

      </nav>

    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="blog-posts">
            {% block content %}

            {% endblock %}
          </div>
        </div>
      </div>

    </div>
  </body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html'%}

{% block content %}
  <form class="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" value="Submit">
  </form>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
  <div class="container">
    <h2>Are you sure to delete {{post.title}}?</h2>
    <form class="" method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Delete">
      <a href="{% url 'blog:post_detail' pk=post.pk %}">Cancel</a>

    </form>

  </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class="container">
    <h1>{{post.title}}</h1>
    <h4>Published Date: {{post.published_date|date:"D M Y"}}</h4>
    <br>
    <p>{{post.text|safe}}</p>
    <p><a class="btn btn-primary" href="{% url 'blog:post_update' pk=post.pk %}">Update</a>
    <a class="btn btn-primary" href="{% url 'blog:post_delete' pk=post.pk %}">Delete</a> </p>
    <div class="jumbotron">

      {% if user.is_authenticated %}
        <p><a href="{% url 'blog:add_comment' pk=post.pk %}">Add Comment</a> </p>
      {% endif %}
      <p>Comments: {{post.approve_comment.count}}</p>
      {% for comment in post.comments.all%}
      {% if comment.approved_comment %}
      <p>Author: {{comment.author}}</p>
      <p>{{comment.text|safe}}</p>
      <p>{{comment.created_date|date:'D M Y'}}</p>
        {% if user.is_authenticated %}
        <p><a href="{% url 'blog:delete_comment' pk=comment.pk %}">delete</a> </p>
        {% endif %}
      {% endif %}
      {% if not comment.approved_comment %}
      <p>Author: {{comment.author}}</p>
      <p>{{comment.text|safe}}</p>
      <p>{{comment.created_date|date:'D M Y'}}<a class="btn btn-primary" href="{% url 'blog:approve_comment' pk=comment.pk %}">Approve</a> </p>

      {% endif %}

      {% endfor %}


    </div>
  </div>

{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html '%}

{% block content %}
  <h1>My drafts List</h1>
  {% for draft in post %}
    <h3>{{draft.title}}</h3>
    <p>{{draft.text|safe}}</p>
    <p> Created Date: {{draft.created_date|date:'D M Y'}} </p>
    <p><a href="{% url 'blog:publish' pk=draft.pk %}" class="btn btn-primary">Publish</a>
        <a class="btn btn-primary" href="{% url 'blog:post_delete' pk=draft.pk %}">Delete</a>
    </p>

  {% endfor %}

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html'%}

{% block content %}
  <h2>
    {% if post.instance.pk %}
      Update Post
      {% else %}
      Create Post
    {% endif %}
  </h2>
  <form class="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" value="Save">

  </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class="container">
    <div class="post">
      {% for post in post %}
        <h3><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a> </h3>
        <div class="date">
          <p>Published Date: {{post.published_date|date:"D M Y"}}</p>
        </div>
        <p><a href="{% url 'blog:post_detail' pk=post.pk %}"></a> Comments: {{post.approve_comment.count}}</p>
      {% endfor %}
    </div>


  </div>
{% endblock %}